<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html >
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Reporte de pruebas</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2.1"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="https://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="https://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    
<style type="text/css" media="screen">
@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap");
    :root{
        --body-font: 'Poppins', sans-serif;

    }
    body{
        margin: var(--header-height) 0 0 0;
        padding: 1rem 1rem 0;
        font-family: var(--body-font);
        background-color: #F9F6FD;
    }    
    .container{
        background-color: white;
        border-radius: 3%;
    }
    .imagenpwst img{
        position:static;
        right: 4%;
        padding-top: 5%;
    }

/* -- report ------------------------------------------------------------------------ */
#total_row  { font-weight: bold; }
.passCase   { color: #5cb85c; }
.failCase   { color: #d9534f; font-weight: bold; }
.errorCase  { color: #f0ad4e; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }
</style>

</head>
<body >
<div class="imagenpwst">
    <img src="https://i.postimg.cc/g2fdS2VC/Recurso-jpg.jpg"width="320"  align="right" >
</div>    
<script language="javascript" type="text/javascript">
output_list = Array();
/*level 
0:Summary //all hiddenRow
1:Failed  //pt hiddenRow, ft none
2:Pass    //pt none, ft hiddenRow
3:All     //pt none, ft none
4:Error  
*/
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level == 2 || level == 0 ) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = 'Hola';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level < 2 || level ==4) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
    }
    detail_class=document.getElementsByClassName('detail');
    //console.log(detail_class.length)
    if (level == 3) {
        for (var i = 0; i < detail_class.length; i++){
            detail_class[i].innerHTML="Ver"
        }
    }
    else{
            for (var i = 0; i < detail_class.length; i++){
            detail_class[i].innerHTML="Ocultar"
        }
    }
}
function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {

        tid0 = 't' + cid.substr(1) + '_' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];

        if (toHide) {
            document.getElementById(tid).className = 'hiddenRow';
            document.getElementById(cid).innerText = "Ver"
        }
        else {
            document.getElementById(tid).className = '';
            document.getElementById(cid).innerText = "Ocultar"
        }
    }
}
function html_escape(s) {
    s = s.replace(/&/g,'&');
    s = s.replace(/</g,'<');
    s = s.replace(/>/g,'>');
    return s;
}
</script>
<div class='heading'>
<h2 style="font-family: Microsoft YaHei">Reporte de pruebas</h4>
<p class='attribute'><strong>Desarrollado por : </strong> Area de Testing PWST</p>
<p class='attribute'><strong>Fecha y hora de inicio : </strong> 2022-10-19 12:09:42</p>
<p class='attribute'><strong>Duracion : </strong> 0:02:14.765236</p>
<p class='attribute'><strong>Resultado : </strong> Total 8，Correctos 1 ，Errores 7 ，Taza de resultado 12.50%</p>

<h3 class='description'>Detalles</h3>
</div>


<p id='show_detail_line'>
<a class="btn btn-primary" href='javascript:showCase(0)'>Resumen 12.50% </a>
<a class="btn btn-warning" href='javascript:showCase(4)'>Errores 7 </a>
<a class="btn btn-danger" href='javascript:showCase(1)'>Fallidos 0 </a>
<a class="btn btn-success" href='javascript:showCase(2)'>Correctos 1 </a>
<a class="btn btn-info" href='javascript:showCase(3)'>Test realizados 8 </a>
</p>
<table id='result_table' class="table table-condensed table-bordered table-hover">
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row' class="text-center success" style="font-weight: bold;font-size: 14px;">
    <td>Caso de Prueba</td>
    <td>Total</td>
    <td>Correctos</td>
    <td>Fallido</td>
    <td>Error</td>
    <td>Detalles</td>
    <td>Captura del error</td>
</tr>

<tr class='errorClass warning'>
    <td>tipopresupuesto.Test: Escenario 1 de tipos de presupuesto</td>
    <td class="text-center">8</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">7</td>
    <td class="text-center"><a href="javascript:showClassDetail('c1',8)" class="detail" id='c1'>Detalles</a></td>
    <td class="text-center"></td>
</tr>

<tr id='pt1_1' class='hiddenRow'>
    <td class='passCase' width='300px'><div class='testcase'>test</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt1_1' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_pt1_1'>Correcto</button>
    <div id='div_pt1_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt1_1' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_pt1_1'>Correcto</button>
    <div id='div_pt1_1' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
pt1_1: 2022-10-19 12:09:43,917 - root - INFO -  Se abre el chrome
2022-10-19 12:09:45,480 - root - INFO -  Entra a la URL
2022-10-19 12:09:45,628 - root - INFO -  Maximiza la pantalla
2022-10-19 12:09:48,700 - root - INFO -  Cambia al frame


    </pre>
    </div>
    </td>
    <td align="right">
        <a hidden="hidden" href="" target="_blank">
            <img src="" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_2' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_000: Ingresa a la base de datos</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_2' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_2'>Error</button>
    <div id='div_ft1_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_2' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_2'>Error</button>
    <div id='div_ft1_2' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_2: 2022-10-19 12:10:02,094 - root - ERROR - No se pudo encontrar el campo para ingresar el usuario, revise si el xpath sigue siendo el mismo, para mas detalles del error consulte el reporte
2022-10-19 12:10:02,095 - root - INFO -  Captura: C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPP\report\img  screen：20221019_12_10_02.png
Traceback (most recent call last):
  File "C:/xampp/htdocs/versiones/automatizaciones/AutoPWST/ingresologin.py", line 26, in ingresologin
    Usuario = self.wait.until(conditions.visibility((By.XPATH, configgnral.id_usuario)))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 78, in until
    value = method(self._driver)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 125, in _predicate
    return _element_if_visible(driver.find_element(*locator))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=106.0.5249.119)
Stacktrace:
Backtrace:
	Ordinal0 [0x00D8DF13+2219795]
	Ordinal0 [0x00D22841+1779777]
	Ordinal0 [0x00C34100+803072]
	Ordinal0 [0x00C29BF2+760818]
	Ordinal0 [0x00C1CD35+707893]
	Ordinal0 [0x00C21122+725282]
	Ordinal0 [0x00C25699+743065]
	Ordinal0 [0x00C35610+808464]
	Ordinal0 [0x00C8E93A+1173818]
	Ordinal0 [0x00C7E616+1107478]
	Ordinal0 [0x00C57F89+950153]
	Ordinal0 [0x00C58F56+954198]
	GetHandleVerifier [0x01082CB2+3040210]
	GetHandleVerifier [0x01072BB4+2974420]
	GetHandleVerifier [0x00E26A0A+565546]
	GetHandleVerifier [0x00E25680+560544]
	Ordinal0 [0x00D29A5C+1808988]
	Ordinal0 [0x00D2E3A8+1827752]
	Ordinal0 [0x00D2E495+1827989]
	Ordinal0 [0x00D380A4+1867940]
	BaseThreadInitThunk [0x7613FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77DD7B5E+286]
	RtlGetAppContainerNamedObjectPath [0x77DD7B2E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPP\testCase\tipopresupuesto.py", line 38, in test_000
    return ingresologin.ingresologin(self)
  File "C:/xampp/htdocs/versiones/automatizaciones/AutoPWST/ingresologin.py", line 35, in ingresologin
    self.driver.get_screenshot_as_file(img_name)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1317, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1353, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1365, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=106.0.5249.119)
Stacktrace:
Backtrace:
	Ordinal0 [0x00D8DF13+2219795]
	Ordinal0 [0x00D22841+1779777]
	Ordinal0 [0x00C34100+803072]
	Ordinal0 [0x00C29BF2+760818]
	Ordinal0 [0x00C1CD35+707893]
	Ordinal0 [0x00C21122+725282]
	Ordinal0 [0x00C25699+743065]
	Ordinal0 [0x00C35610+808464]
	Ordinal0 [0x00C8E93A+1173818]
	Ordinal0 [0x00C7E616+1107478]
	Ordinal0 [0x00C57F89+950153]
	Ordinal0 [0x00C58F56+954198]
	GetHandleVerifier [0x01082CB2+3040210]
	GetHandleVerifier [0x01072BB4+2974420]
	GetHandleVerifier [0x00E26A0A+565546]
	GetHandleVerifier [0x00E25680+560544]
	Ordinal0 [0x00D29A5C+1808988]
	Ordinal0 [0x00D2E3A8+1827752]
	Ordinal0 [0x00D2E495+1827989]
	Ordinal0 [0x00D380A4+1867940]
	BaseThreadInitThunk [0x7613FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77DD7B5E+286]
	RtlGetAppContainerNamedObjectPath [0x77DD7B2E+238]



    </pre>
    </div>
    </td>
    <td align="right">
        <a  href="../../../../img/20221019_12_10_02.png" target="_blank">
            <img src="../../../../img/20221019_12_10_02.png" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_3' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_001: Abre menu y ejecuta pantalla</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_3' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_3'>Error</button>
    <div id='div_ft1_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_3' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_3'>Error</button>
    <div id='div_ft1_3' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_3: 2022-10-19 12:10:22,982 - root - ERROR - No se pudo encontrar el botón para desplegar el menu completo, validar que la acción anterior haya finalizado,que el xpath sea el correcto o que la página no presente lentitud
2022-10-19 12:10:22,985 - root - INFO -  Captura: C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPP\report\img  screen：20221019_12_10_22.png
Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPP\testCase\ingresopantalla.py", line 20, in ingresopantalla
    Sandwich = self.wait.until(conditions.visibility((By.XPATH, Configuracion.btn_sandwich)))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 78, in until
    value = method(self._driver)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 125, in _predicate
    return _element_if_visible(driver.find_element(*locator))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=106.0.5249.119)
Stacktrace:
Backtrace:
	Ordinal0 [0x00D8DF13+2219795]
	Ordinal0 [0x00D22841+1779777]
	Ordinal0 [0x00C34100+803072]
	Ordinal0 [0x00C29BF2+760818]
	Ordinal0 [0x00C1CD35+707893]
	Ordinal0 [0x00C21122+725282]
	Ordinal0 [0x00C25699+743065]
	Ordinal0 [0x00C35610+808464]
	Ordinal0 [0x00C8E93A+1173818]
	Ordinal0 [0x00C7E616+1107478]
	Ordinal0 [0x00C57F89+950153]
	Ordinal0 [0x00C58F56+954198]
	GetHandleVerifier [0x01082CB2+3040210]
	GetHandleVerifier [0x01072BB4+2974420]
	GetHandleVerifier [0x00E26A0A+565546]
	GetHandleVerifier [0x00E25680+560544]
	Ordinal0 [0x00D29A5C+1808988]
	Ordinal0 [0x00D2E3A8+1827752]
	Ordinal0 [0x00D2E495+1827989]
	Ordinal0 [0x00D380A4+1867940]
	BaseThreadInitThunk [0x7613FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77DD7B5E+286]
	RtlGetAppContainerNamedObjectPath [0x77DD7B2E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPP\testCase\tipopresupuesto.py", line 42, in test_001
    return ingresopantalla.ingresopantalla(self)
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPP\testCase\ingresopantalla.py", line 32, in ingresopantalla
    self.driver.get_screenshot_as_file(img_name)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1317, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1353, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1365, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=106.0.5249.119)
Stacktrace:
Backtrace:
	Ordinal0 [0x00D8DF13+2219795]
	Ordinal0 [0x00D22841+1779777]
	Ordinal0 [0x00C34100+803072]
	Ordinal0 [0x00C29BF2+760818]
	Ordinal0 [0x00C1CD35+707893]
	Ordinal0 [0x00C21122+725282]
	Ordinal0 [0x00C25699+743065]
	Ordinal0 [0x00C35610+808464]
	Ordinal0 [0x00C8E93A+1173818]
	Ordinal0 [0x00C7E616+1107478]
	Ordinal0 [0x00C57F89+950153]
	Ordinal0 [0x00C58F56+954198]
	GetHandleVerifier [0x01082CB2+3040210]
	GetHandleVerifier [0x01072BB4+2974420]
	GetHandleVerifier [0x00E26A0A+565546]
	GetHandleVerifier [0x00E25680+560544]
	Ordinal0 [0x00D29A5C+1808988]
	Ordinal0 [0x00D2E3A8+1827752]
	Ordinal0 [0x00D2E495+1827989]
	Ordinal0 [0x00D380A4+1867940]
	BaseThreadInitThunk [0x7613FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77DD7B5E+286]
	RtlGetAppContainerNamedObjectPath [0x77DD7B2E+238]



    </pre>
    </div>
    </td>
    <td align="right">
        <a  href="../../../../img/20221019_12_10_22.png" target="_blank">
            <img src="../../../../img/20221019_12_10_22.png" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_4' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_002: Abre la ventana de nuevo y crear un registro</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_4' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_4'>Error</button>
    <div id='div_ft1_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_4' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_4'>Error</button>
    <div id='div_ft1_4' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_4: 2022-10-19 12:10:43,746 - root - ERROR - La pantalla ejecutada no es correcta, validar que la acción anterior haya finalizado,que el xpath sea el correcto o que la página no presente lentitud
2022-10-19 12:10:43,748 - root - INFO -  Captura: C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPP\report\img  screen：20221019_12_10_43.png
Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPP\testCase\nuevoregistro.py", line 21, in nuevoregistro
    Crea = self.wait.until(conditions.visibility((By.XPATH, Configuracion.titulo_nuevo))).text
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 78, in until
    value = method(self._driver)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 125, in _predicate
    return _element_if_visible(driver.find_element(*locator))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=106.0.5249.119)
Stacktrace:
Backtrace:
	Ordinal0 [0x00D8DF13+2219795]
	Ordinal0 [0x00D22841+1779777]
	Ordinal0 [0x00C34100+803072]
	Ordinal0 [0x00C29BF2+760818]
	Ordinal0 [0x00C1CD35+707893]
	Ordinal0 [0x00C21122+725282]
	Ordinal0 [0x00C25699+743065]
	Ordinal0 [0x00C35610+808464]
	Ordinal0 [0x00C8E93A+1173818]
	Ordinal0 [0x00C7E616+1107478]
	Ordinal0 [0x00C57F89+950153]
	Ordinal0 [0x00C58F56+954198]
	GetHandleVerifier [0x01082CB2+3040210]
	GetHandleVerifier [0x01072BB4+2974420]
	GetHandleVerifier [0x00E26A0A+565546]
	GetHandleVerifier [0x00E25680+560544]
	Ordinal0 [0x00D29A5C+1808988]
	Ordinal0 [0x00D2E3A8+1827752]
	Ordinal0 [0x00D2E495+1827989]
	Ordinal0 [0x00D380A4+1867940]
	BaseThreadInitThunk [0x7613FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77DD7B5E+286]
	RtlGetAppContainerNamedObjectPath [0x77DD7B2E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPP\testCase\tipopresupuesto.py", line 46, in test_002
    return nuevoregistro.nuevoregistro(self)
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPP\testCase\nuevoregistro.py", line 31, in nuevoregistro
    self.driver.get_screenshot_as_file(img_name)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1317, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1353, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1365, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=106.0.5249.119)
Stacktrace:
Backtrace:
	Ordinal0 [0x00D8DF13+2219795]
	Ordinal0 [0x00D22841+1779777]
	Ordinal0 [0x00C34100+803072]
	Ordinal0 [0x00C29BF2+760818]
	Ordinal0 [0x00C1CD35+707893]
	Ordinal0 [0x00C21122+725282]
	Ordinal0 [0x00C25699+743065]
	Ordinal0 [0x00C35610+808464]
	Ordinal0 [0x00C8E93A+1173818]
	Ordinal0 [0x00C7E616+1107478]
	Ordinal0 [0x00C57F89+950153]
	Ordinal0 [0x00C58F56+954198]
	GetHandleVerifier [0x01082CB2+3040210]
	GetHandleVerifier [0x01072BB4+2974420]
	GetHandleVerifier [0x00E26A0A+565546]
	GetHandleVerifier [0x00E25680+560544]
	Ordinal0 [0x00D29A5C+1808988]
	Ordinal0 [0x00D2E3A8+1827752]
	Ordinal0 [0x00D2E495+1827989]
	Ordinal0 [0x00D380A4+1867940]
	BaseThreadInitThunk [0x7613FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77DD7B5E+286]
	RtlGetAppContainerNamedObjectPath [0x77DD7B2E+238]



    </pre>
    </div>
    </td>
    <td align="right">
        <a  href="../../../../img/20221019_12_10_43.png" target="_blank">
            <img src="../../../../img/20221019_12_10_43.png" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_5' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_003: Repetir el registro creado anteriormente</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_5' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_5'>Error</button>
    <div id='div_ft1_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_5' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_5'>Error</button>
    <div id='div_ft1_5' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_5: 2022-10-19 12:11:04,606 - root - ERROR - No se dió click al botón Refrescar, validar que la acción anterior haya finalizado,que el xpath sea el correcto o que la página no presente lentitud
2022-10-19 12:11:04,607 - root - INFO -  Captura: C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPP\report\img  screen：20221019_12_11_04.png
Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPP\testCase\repetirregistro.py", line 22, in repetirregistro
    Refresca = self.wait.until(conditions.visibility((By.XPATH, Configuracion.btn_Refresca)))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 78, in until
    value = method(self._driver)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 125, in _predicate
    return _element_if_visible(driver.find_element(*locator))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=106.0.5249.119)
Stacktrace:
Backtrace:
	Ordinal0 [0x00D8DF13+2219795]
	Ordinal0 [0x00D22841+1779777]
	Ordinal0 [0x00C34100+803072]
	Ordinal0 [0x00C29BF2+760818]
	Ordinal0 [0x00C1CD35+707893]
	Ordinal0 [0x00C21122+725282]
	Ordinal0 [0x00C25699+743065]
	Ordinal0 [0x00C35610+808464]
	Ordinal0 [0x00C8E93A+1173818]
	Ordinal0 [0x00C7E616+1107478]
	Ordinal0 [0x00C57F89+950153]
	Ordinal0 [0x00C58F56+954198]
	GetHandleVerifier [0x01082CB2+3040210]
	GetHandleVerifier [0x01072BB4+2974420]
	GetHandleVerifier [0x00E26A0A+565546]
	GetHandleVerifier [0x00E25680+560544]
	Ordinal0 [0x00D29A5C+1808988]
	Ordinal0 [0x00D2E3A8+1827752]
	Ordinal0 [0x00D2E495+1827989]
	Ordinal0 [0x00D380A4+1867940]
	BaseThreadInitThunk [0x7613FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77DD7B5E+286]
	RtlGetAppContainerNamedObjectPath [0x77DD7B2E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPP\testCase\tipopresupuesto.py", line 50, in test_003
    return repetirregistro.repetirregistro(self)
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPP\testCase\repetirregistro.py", line 33, in repetirregistro
    self.driver.get_screenshot_as_file(img_name)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1317, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1353, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1365, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=106.0.5249.119)
Stacktrace:
Backtrace:
	Ordinal0 [0x00D8DF13+2219795]
	Ordinal0 [0x00D22841+1779777]
	Ordinal0 [0x00C34100+803072]
	Ordinal0 [0x00C29BF2+760818]
	Ordinal0 [0x00C1CD35+707893]
	Ordinal0 [0x00C21122+725282]
	Ordinal0 [0x00C25699+743065]
	Ordinal0 [0x00C35610+808464]
	Ordinal0 [0x00C8E93A+1173818]
	Ordinal0 [0x00C7E616+1107478]
	Ordinal0 [0x00C57F89+950153]
	Ordinal0 [0x00C58F56+954198]
	GetHandleVerifier [0x01082CB2+3040210]
	GetHandleVerifier [0x01072BB4+2974420]
	GetHandleVerifier [0x00E26A0A+565546]
	GetHandleVerifier [0x00E25680+560544]
	Ordinal0 [0x00D29A5C+1808988]
	Ordinal0 [0x00D2E3A8+1827752]
	Ordinal0 [0x00D2E495+1827989]
	Ordinal0 [0x00D380A4+1867940]
	BaseThreadInitThunk [0x7613FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77DD7B5E+286]
	RtlGetAppContainerNamedObjectPath [0x77DD7B2E+238]



    </pre>
    </div>
    </td>
    <td align="right">
        <a  href="../../../../img/20221019_12_11_04.png" target="_blank">
            <img src="../../../../img/20221019_12_11_04.png" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_6' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_004: Modificar el registro</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_6' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_6'>Error</button>
    <div id='div_ft1_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_6' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_6'>Error</button>
    <div id='div_ft1_6' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_6: 2022-10-19 12:11:25,408 - root - ERROR - No se dió click al botón Refrescar, validar que la acción anterior haya finalizado,que el xpath sea el correcto o que la página no presente lentitud
2022-10-19 12:11:25,408 - root - INFO -  Captura: C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPP\report\img  screen：20221019_12_11_25.png
Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPP\testCase\modificarregistro.py", line 22, in modificarregistro
    Refresca2 = self.wait.until(conditions.visibility((By.XPATH, Configuracion.btn_Refresca)))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 78, in until
    value = method(self._driver)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 125, in _predicate
    return _element_if_visible(driver.find_element(*locator))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=106.0.5249.119)
Stacktrace:
Backtrace:
	Ordinal0 [0x00D8DF13+2219795]
	Ordinal0 [0x00D22841+1779777]
	Ordinal0 [0x00C34100+803072]
	Ordinal0 [0x00C29BF2+760818]
	Ordinal0 [0x00C1CD35+707893]
	Ordinal0 [0x00C21122+725282]
	Ordinal0 [0x00C25699+743065]
	Ordinal0 [0x00C35610+808464]
	Ordinal0 [0x00C8E93A+1173818]
	Ordinal0 [0x00C7E616+1107478]
	Ordinal0 [0x00C57F89+950153]
	Ordinal0 [0x00C58F56+954198]
	GetHandleVerifier [0x01082CB2+3040210]
	GetHandleVerifier [0x01072BB4+2974420]
	GetHandleVerifier [0x00E26A0A+565546]
	GetHandleVerifier [0x00E25680+560544]
	Ordinal0 [0x00D29A5C+1808988]
	Ordinal0 [0x00D2E3A8+1827752]
	Ordinal0 [0x00D2E495+1827989]
	Ordinal0 [0x00D380A4+1867940]
	BaseThreadInitThunk [0x7613FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77DD7B5E+286]
	RtlGetAppContainerNamedObjectPath [0x77DD7B2E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPP\testCase\tipopresupuesto.py", line 54, in test_004
    return modificarregistro.modificarregistro(self)
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPP\testCase\modificarregistro.py", line 33, in modificarregistro
    self.driver.get_screenshot_as_file(img_name)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1317, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1353, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1365, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=106.0.5249.119)
Stacktrace:
Backtrace:
	Ordinal0 [0x00D8DF13+2219795]
	Ordinal0 [0x00D22841+1779777]
	Ordinal0 [0x00C34100+803072]
	Ordinal0 [0x00C29BF2+760818]
	Ordinal0 [0x00C1CD35+707893]
	Ordinal0 [0x00C21122+725282]
	Ordinal0 [0x00C25699+743065]
	Ordinal0 [0x00C35610+808464]
	Ordinal0 [0x00C8E93A+1173818]
	Ordinal0 [0x00C7E616+1107478]
	Ordinal0 [0x00C57F89+950153]
	Ordinal0 [0x00C58F56+954198]
	GetHandleVerifier [0x01082CB2+3040210]
	GetHandleVerifier [0x01072BB4+2974420]
	GetHandleVerifier [0x00E26A0A+565546]
	GetHandleVerifier [0x00E25680+560544]
	Ordinal0 [0x00D29A5C+1808988]
	Ordinal0 [0x00D2E3A8+1827752]
	Ordinal0 [0x00D2E495+1827989]
	Ordinal0 [0x00D380A4+1867940]
	BaseThreadInitThunk [0x7613FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77DD7B5E+286]
	RtlGetAppContainerNamedObjectPath [0x77DD7B2E+238]



    </pre>
    </div>
    </td>
    <td align="right">
        <a  href="../../../../img/20221019_12_11_25.png" target="_blank">
            <img src="../../../../img/20221019_12_11_25.png" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_7' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_005: Eliminar el registro creado</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_7' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_7'>Error</button>
    <div id='div_ft1_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_7' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_7'>Error</button>
    <div id='div_ft1_7' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_7: 2022-10-19 12:11:46,222 - root - ERROR - No se dió click al botón Refrescar, validar que la acción anterior haya finalizado,que el xpath sea el correcto o que la página no presente lentitud
2022-10-19 12:11:46,224 - root - INFO -  Captura: C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPP\report\img  screen：20221019_12_11_46.png
Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPP\testCase\eliminarregistro.py", line 22, in eliminarregistro
    Refresca3 = self.wait.until(conditions.visibility((By.XPATH, Configuracion.btn_Refresca)))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 78, in until
    value = method(self._driver)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 125, in _predicate
    return _element_if_visible(driver.find_element(*locator))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=106.0.5249.119)
Stacktrace:
Backtrace:
	Ordinal0 [0x00D8DF13+2219795]
	Ordinal0 [0x00D22841+1779777]
	Ordinal0 [0x00C34100+803072]
	Ordinal0 [0x00C29BF2+760818]
	Ordinal0 [0x00C1CD35+707893]
	Ordinal0 [0x00C21122+725282]
	Ordinal0 [0x00C25699+743065]
	Ordinal0 [0x00C35610+808464]
	Ordinal0 [0x00C8E93A+1173818]
	Ordinal0 [0x00C7E616+1107478]
	Ordinal0 [0x00C57F89+950153]
	Ordinal0 [0x00C58F56+954198]
	GetHandleVerifier [0x01082CB2+3040210]
	GetHandleVerifier [0x01072BB4+2974420]
	GetHandleVerifier [0x00E26A0A+565546]
	GetHandleVerifier [0x00E25680+560544]
	Ordinal0 [0x00D29A5C+1808988]
	Ordinal0 [0x00D2E3A8+1827752]
	Ordinal0 [0x00D2E495+1827989]
	Ordinal0 [0x00D380A4+1867940]
	BaseThreadInitThunk [0x7613FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77DD7B5E+286]
	RtlGetAppContainerNamedObjectPath [0x77DD7B2E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPP\testCase\tipopresupuesto.py", line 58, in test_005
    return eliminarregistro.eliminarregistro(self)
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPP\testCase\eliminarregistro.py", line 32, in eliminarregistro
    self.driver.get_screenshot_as_file(img_name)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1317, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1353, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1365, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=106.0.5249.119)
Stacktrace:
Backtrace:
	Ordinal0 [0x00D8DF13+2219795]
	Ordinal0 [0x00D22841+1779777]
	Ordinal0 [0x00C34100+803072]
	Ordinal0 [0x00C29BF2+760818]
	Ordinal0 [0x00C1CD35+707893]
	Ordinal0 [0x00C21122+725282]
	Ordinal0 [0x00C25699+743065]
	Ordinal0 [0x00C35610+808464]
	Ordinal0 [0x00C8E93A+1173818]
	Ordinal0 [0x00C7E616+1107478]
	Ordinal0 [0x00C57F89+950153]
	Ordinal0 [0x00C58F56+954198]
	GetHandleVerifier [0x01082CB2+3040210]
	GetHandleVerifier [0x01072BB4+2974420]
	GetHandleVerifier [0x00E26A0A+565546]
	GetHandleVerifier [0x00E25680+560544]
	Ordinal0 [0x00D29A5C+1808988]
	Ordinal0 [0x00D2E3A8+1827752]
	Ordinal0 [0x00D2E495+1827989]
	Ordinal0 [0x00D380A4+1867940]
	BaseThreadInitThunk [0x7613FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77DD7B5E+286]
	RtlGetAppContainerNamedObjectPath [0x77DD7B2E+238]



    </pre>
    </div>
    </td>
    <td align="right">
        <a  href="../../../../img/20221019_12_11_46.png" target="_blank">
            <img src="../../../../img/20221019_12_11_46.png" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_8' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_006: Cerrar_Navegador</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_8' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_8'>Error</button>
    <div id='div_ft1_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_8' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_8'>Error</button>
    <div id='div_ft1_8' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_8: Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPP\testCase\tipopresupuesto.py", line 62, in test_006
    self.driver.close()
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 937, in close
    self.execute(Command.CLOSE)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=106.0.5249.119)
Stacktrace:
Backtrace:
	Ordinal0 [0x00D8DF13+2219795]
	Ordinal0 [0x00D22841+1779777]
	Ordinal0 [0x00C34100+803072]
	Ordinal0 [0x00C29BF2+760818]
	Ordinal0 [0x00C1C220+705056]
	Ordinal0 [0x00C84F05+1134341]
	Ordinal0 [0x00C7E7C3+1107907]
	Ordinal0 [0x00C57F89+950153]
	Ordinal0 [0x00C58F56+954198]
	GetHandleVerifier [0x01082CB2+3040210]
	GetHandleVerifier [0x01072BB4+2974420]
	GetHandleVerifier [0x00E26A0A+565546]
	GetHandleVerifier [0x00E25680+560544]
	Ordinal0 [0x00D29A5C+1808988]
	Ordinal0 [0x00D2E3A8+1827752]
	Ordinal0 [0x00D2E495+1827989]
	Ordinal0 [0x00D380A4+1867940]
	BaseThreadInitThunk [0x7613FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77DD7B5E+286]
	RtlGetAppContainerNamedObjectPath [0x77DD7B2E+238]



    </pre>
    </div>
    </td>
    <td align="right">
        <a hidden="hidden" href="" target="_blank">
            <img src="" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='total_row' class="text-center active">
    <td>Caso de prueba</td>
    <td>8</td>
    <td>1</td>
    <td>0</td>
    <td>7</td>
    <td>Taza de resultado：12.50%</td>
    <td> <a href="" target="_blank"></a></td>
</tr>
</table>

<div id='ending'> </div>
    <div style=" position:fixed;right:50px; bottom:30px; width:20px; height:20px;cursor:pointer">
    <a href="#"><span class="glyphicon glyphicon-eject" style = "font-size:30px;" aria-hidden="true">
    </span></a></div>
    
</body>
</html>
